# Generated by Django 2.1.7 on 2019-03-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnarie', '0002_auto_20190311_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
